### PR TITLE
fix building with libxml 2.12.0

### PR DESCRIPTION
**Pull request by raveit65**
```
coco-theme.c: In function 'set_notification_text':
coco-theme.c:509:9: error: implicit declaration of function 'xmlInitParser' [-Werror=implicit-function-declaration]
509 |         xmlInitParser();
|         ^~~~~~~~~~~~~
coco-theme.c:513:15: error: implicit declaration of function 'xmlReadMemory'; did you mean 'xmlInitMemory'? [-Werror=implicit-function-declaration]
513 |         doc = xmlReadMemory(str, (int) str_len, "noname.xml", NULL, 0);
|               ^~~~~~~~~~~~~
|               xmlInitMemory
coco-theme.c:513:13: warning: assignment to 'xmlDocPtr' {aka 'struct _xmlDoc *'} from 'int' makes pointer from integer without a cast [-Wint-conversion]
513 |         doc = xmlReadMemory(str, (int) str_len, "noname.xml", NULL, 0);
|             ^
coco-theme.c:561:9: error: implicit declaration of function 'xmlCleanupParser' [-Werror=implicit-function-declaration]
561 |         xmlCleanupParser ();
|         ^~~~~~~~~~~~~~~~
```
Same warnings are in other themes.
Successful build with libxml-2.12.0 from fedora-rawhide at fedora build-server.
https://koji.fedoraproject.org/koji/taskinfo?taskID=109502322
https://src.fedoraproject.org/rpms/mate-notification-daemon/blob/rawhide/f/mate-notification-daemon.spec#_32

### CODE REVIEW

**Review by lukefromdc — APPROVED** [review]
Builds fine here, but that's with libxml 2.9 before changes broke the incorrect include logic we've been using in the past. A build with 2.12 will confirm this to be ready,
